### ISSUE TITLE
HTML5 SVG

### ISSUE THREAD

**Issue by xiaoyann** [striverx/notes#12]
```
将svg保存为文件使用时需要加个namespace
<svg width="" height="" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>
```

| SVG | attribute | note |
| --- | --- | --- |
| rect | width,height,x,y,fill,stroke,stroke-width |  |
| circle | cx,cy,r,stroke,stroke-width,fill |  |
| g | transform | 组,transform的值 translate scale rotate |
| defs |  | 预先定义待以后使用的元素 |
| use |  | 使用defs，smybol里的东东 |

**Comment by striver-x** [comment]
fdsfs
